### ISSUE TITLE
Empty tracklist.txt

### ISSUE THREAD

**Issue by wting** [abhshkdz/8tracks-downloader#4]
```bash
╭─ting@noa ~/code/8tracks-downloader ‹python-3.3.1› ‹ruby-1.9.3› ‹master› 
╰─➤  ./script.sh http://8tracks.com/joannekim/indie-vs-hip-hop 980936                                                        2013.04.11 15:14:30 CDT 
mix=indie-vs-hip-hop
mix_id=980936
tracks=33
tracks_played=http://8tracks.com/sets/980936/tracks_played?mix_id=980936&reverse=true&format=jsonh
Initializing download: 

Initializing download: 

╭─ting@noa ~/code/8tracks-downloader ‹python-3.3.1› ‹ruby-1.9.3› ‹master*› 
╰─➤  cat indie-vs-hip-hop/tracklist.txt                                                                                      2013.04.11 15:14:52 CDT 
Filename / Song / Artist / Album
|||
|||
```

![8tracks](https://f.cloud.github.com/assets/622170/369989/ade0c950-a2e4-11e2-95d2-640db842f997.png)

**Comment by DomSavd** [comment]
```

Hi have  a problem running the script...

Im setup on Ubuntu and ive install axel and underscore-cli. I also try to chmod -x my script in order to assure that the script have the right to write in the folder. But it<s still not working...

**Here is the response i get from the terminal:**
mix=return-of-the-boom-bap
mix_id=148155
tracks=11
11
tracks_played=http://8tracks.com/sets/320341302/tracks_played?mix_id=148155&reverse=true&format=jsonh
mkdir: cannot create directory ‘return-of-the-boom-bap’: File exists
./script.sh: line 19: ((: i<11
11: syntax error in expression (error token is "11")
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
Initializing download: 

Can you help me please? I really need this it to works.

Thanks!



```

**Comment by DomSavd** [comment]
And when i delete the old folder here run the script an other time: 

sudo ./script.sh https://8tracks.com/unblack/return-of-the-boom-bap 320341302
mix=return-of-the-boom-bap
mix_id=148155
tracks=11
11
tracks_played=http://8tracks.com/sets/320341302/tracks_played?mix_id=148155&reverse=true&format=jsonh
./script.sh: line 19: ((: i<11
11: syntax error in expression (error token is "11")
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
cat: last.json: No such file or directory
Error while parsing STDIN: File is empty!
Initializing download: 


Thanks!

**Comment by abhshkdz** [comment]
@DomSavd There was a minor change in their markup, causing the bug. Should work now.

I'm pleasantly surprised to discover that this still works even after 3+ years since I last used (and worked on) this script :)

**Comment by DomSavd** [comment]
hehe thanks ill try that 2night!! by the way nice script! :)

**Comment by DomSavd** [comment]
it works! thanks you! im looking to make it loop in a list of mixurl and even better by retrieving the list of url from a search query by tag. The thing is i have to get familiar with your shell script. Do you think this could be possible?

**Comment by DomSavd** [comment]
Also i noticed the script is not getting all the tracks from the mix... you have an idea on how to fix it? Thank you!

**Comment by DomSavd** [comment]
What i understand from your script is that you recover the number of tracks and after that your looping a request with next_url query and retrieve to response info until you have passed the number of tracks in the mix.

The thing I dont understand is where the script bypass the limit of three skip?

Thank you!
